### ISSUE TITLE
Planned Feature: Working with Multiple structures at a time

### ISSUE THREAD

**Issue by gdmhrosch** [rostock/CityJSONEditor#1]
As of now, the user can only import and edit one building at a time. We plan on expanding on this, so that multiple Buildings can be in the project as a scene.

**Comment by Flawks** [comment]
The import of multiple buildings would be a really great feature! Could you provide some insights if it will be available soon? If there's no such update planned for the nearest future maybe you could provide some hints where in the code it could be added? Thank you!

**Comment by gdmhrosch** [comment]
We are currently working on a rework/restructure of the addon that will incorporate most of the planned features. It is a lower priority side project of ours though so it is unlikely to be finished within the next two months i think. 
The import of multiple buildings can't be done right now because the scene is deleted when a new import is made. (see line 185 of `core/objects.py`). This is done because the current implementation relies on a somewhat suboptimal construct of how the UTM coordinates are saved in the file which we kept from the addon we based ours off of. Another aspect is how the local coordinates are transformed when exporting to CityJSON. We basically have to redo/reorganize the whole import and export structure. (all found in `core/objects.py` in the respective classes)
